export const CHAT_ACTION_TYPE = {
  APPEND_MESSAGE: "APPEND_MESSAGE",
  IS_TYPING: "IS_TYPING",
  STOP_TYPING: "STOP_TYPING",
  IS_JOINED: "IS_JOINED",
  IS_LEFT: "IS_LEFT",
  IS_LEFT: "IS_LEFT",
  ADD_USER: "ADD_USER",
  REMOVE_USER: "REMOVE_USER",
  GET_USERS_IN_ROOM: "GET_USERS_IN_ROOM",
  SET_USERS_IN_ROOM: "SET_USERS_IN_ROOM",
};
