export const EVENTS_ACTION_TYPE = {
  SET_EVENTS: "SET_EVENTS",
  ADD_EVENT: "ADD_EVENT",
  UPDATE_EVENTS_LIST: "UPDATE_EVENTS_LIST",
  GET_USER_EVENTS: "GET_USER_EVENTS",
  UPDATE_USER_EVENTS: "UPDATE_USER_EVENTS",
  EVENT_QUERY: "EVENT_QUERY",
};
